ecommerce_project/cart_app/urls.py
from django.urls import path 
from . import views

app_name='cart_app'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name ='add_cart'),
    path('',views.cart_details,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='remove_cart'),
    path('delete/<int:product_id>',views.cart_delete,name='delete_cart'),
]

ecommerce_project/ecommerce_app/urls.py
from django.urls import path

from ecommerce_app import views
app_name='ecommerce_app'

urlpatterns = [
    path('',views.allProductCat,name='allProductCat'),
    path('<slug:c_slug>/',views.allProductCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetails,name="proCatDetails"),
]

ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('ecommerce_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_project/search_app/urls.py
from django.urls import path 
from . import views

app_name='search_app'

urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

ecommerce_project/cart_app/models.py
from django.db import models
from ecommerce_app.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)
    
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/ecommerce_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length= 250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecommerce_app:products_by_category',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    def get_url(self):
        return reverse('ecommerce_app:proCatDetails',args=[self.category.slug ,self.slug])
    
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
        
    def __str__(self):
        return '{}'.format(self.name)

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/cart_app/views.py
from django.shortcuts import get_object_or_404, render,redirect
from ecommerce_app.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

#Create a Cart id for a session
def _cart_Id(request):
    cart=request.session.session_key
    if not cart :
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_Id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_Id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,cart=cart,quantity=1
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')    

def cart_details(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_Id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(total=total,cart_items=cart_items,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_Id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_items=CartItem.objects.get(product=product,cart=cart)
    if cart_items.quantity > 1:
        cart_items.quantity -= 1
        cart_items.save()
    else:
        cart_items.delete()
    return redirect('cart_app:cart_detail')

def cart_delete(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_Id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_items=CartItem.objects.get(product=product,cart=cart)
    cart_items.delete()
    return redirect('cart_app:cart_detail')

ecommerce_project/ecommerce_app/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def home(request):
    return render(request,'home.html')
def allProductCat(request,c_slug=None):
    c_page=None #category_page
    product_list=None
    # Check if a category slug is provided
    if c_slug !=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        # If no category slug is provided, get all available products
        product_list=Product.objects.all().filter(available=True)
     # Create a Paginator object with 6 products per page
    paginator=Paginator(product_list,6)
    try:
         # Try to get the page number from the request's GET parameters
        page=int(request.GET.get('page','1'))
    except:
        # If an exception occurs (e.g., if the page parameter is not an integer), set page to 1
        page=1
    try:
         # Try to get the requested page of products using the Paginator
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        # If the requested page is empty or invalid, get the last page of products
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def proDetails(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce_project/search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q
# Create your views here.
def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})    
        

ecommerce_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ba5a227daf.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<div class="container-fluid">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        This is the cart page. Proceed to review your items and place the order
{% endblock %}

{% block title %}
    Cart - Tamarao Pvt Limited
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"> Your Cart is Empty </h1>
        <br>
        <p>
            Please Click <a href="{% url 'ecommerce_app:allProductCat' %}">Here</a> to Continue Shoping
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"> Your Shopping Cart</h1> <br>
    </div>
    <div class="row mx-auto" >
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                    Your Items
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="cart_item.product.get_absolute.url"><img src="{{cart_item.product.image.url}}" alt="" style="width:120px;height:100px;" class="float-left custom_image"></img></a>

                            </td>
                            <td class="text-left">
                                {{cart_item.product.name}}
                                <br>
                                SKU: {{cart_item.product.id}}
                                <br>
                                Price: ₹{{cart_item.product.price}}
                                <br>
                                Qty: {{cart_item.quantity}} x ₹{{cart_item}}           
                            </td>
                            <td>
                                ₹ {{cart_item.sub_total}}
                            </td>
                            {% if cart_item.product.stock > cart_item.quantity %}
                            <td>
                                <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-regular fa-plus custom_icon"></i></a>
                                &nbsp;
                                <a href="{% url 'cart_app:remove_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                &nbsp;
                                <a href="{% url 'cart_app:delete_cart' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                            </td>
                            {% else %}
                            <td>
                                &nbsp;
                                <a href="{% url 'cart_app:remove_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                &nbsp;
                                <a href="{% url 'cart_app:delete_cart' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please review your shopping cart items bfore proceeding with the order payment.
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                                Grand Total: ₹ {{total}}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecommerce_app:allProductCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcomes to ABC store where you can buys different items...
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}} - ABC Store
    {% else %}
        See our New Collection - ABC Store
    {% endif %}
{% endblock %}
{% block content %}
{% if category %}
 <div>
     <div>
            <p>
                <a href="{% url 'ecommerce_app:allProductCat' %}" alt="{{category.name}}"></a>

            </p>
     </div>
 </div>
{% endif %}
<div>
    {% if category %}
    <img src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1>{{category.name}}</h1>
    <p> {{category.description}}</p>
</div>
    {% else %}
<div class="my-image">
    <img src="{% static 'img/banner.jpg' %}" alt="our products" width="100%" height="400px">
</div>
<div class ="container">
    <div class="row my_row_class">
        <div class="mx_auto">
            <h1 class="text-center">Our Products Collections</h1>
            <p class="text-justify" >Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </div>
    </div>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for products in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4" >
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.image.url}}" alt="{{products.name}}"></a>
                <div class="card-body">
                    <h4>{{products.name}}</h4>
                    <p>₹{{products.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}  
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerce_project/templates/footer.html
<div class ="footer navbar-fixed-bottom my_footer">
    <h5 class="text-center">&copy; All Rights Received for Tamarao@Coffee</h5>
</div>

ecommerce_project/templates/header.html
{% load static %}

<header>
                <center>
 <a href="{% url 'ecommerce_app:allProductCat' %}"> <img src="{% static 'img/logo.png' %}" alt="logimg" width="100px" height="100px"></a>
                </center>
</header>

ecommerce_project/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Title</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

ecommerce_project/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid store_name">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'ecommerce_app:allProductCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerce_app' in request.path %} active {% endif %} ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecommerce_app:allProductCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart_app:cart_detail' %}" > <i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        {{ product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
    {{product.name}} - ABC Store
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'ecommerce_app:allProductCat' %}">Home</a>| <a href="{{prdouct.category.geturl}}">{{product.category}}</a>|{{product.name}} </p>
    </div>

    <div class="container">
        <br>
        <div class="row">
            <div class ="col-12 col-sm-12 col-md-12 col-lg-6 text-center ">
                <div class="min-width:18rem">
                    <img src="{{product.image.url}}" alt="{{product.name}}">
                </div>
            </div>

                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <h1 class="my_prod_title">{{product.name}}</h1>
                    <p style="font-size:22px;">₹{{product.price}}</p>
                    <p style="font-size:25px;">Product Description </p>
                    <p class="text-justify my_prod_class">{{product.description}}</p>
                    <p class="text-justify my_prod_class">Stock: {{product.stock}}</p>
                    {% if product.stock <= 0  %}
                        <p class="text-justify">
                            <b> Out of Stock</b>
                        </p>
                    {% else %}
                    <p>
                        <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}">Add to Cart </a>
                    </p>
                    {% endif %}
                </div>

        </div>
    </div>
</div>

{% endblock %}

ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have Variety of Tea's to offer..
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"> You have search for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for products in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4" >
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.image.url}}" alt="{{products.name}}"></a>
                <div class="card-body">
                    <h4>{{products.name}}</h4>
                    <p>₹{{products.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div>
            <p class="text-center my_search_text ">0 Result Found </p>
        </div>
        {% endfor %}
        
    </div>
</div>
{% endblock %}